language: node_js
node_js:
  - '7'
  script:
  - npm run fastbuild
before_deploy:
  - cd packages && cd office-ui-fabric-react
deploy:
  provider: azure_web_apps
  skip_cleanup: true
  verbose: true
  on:
    all_branches: true
