language: node_js
node_js:
  - '7'
script:
  - npm run buildfast
before_deploy:
  cd packages\office-ui-fabric-react
deploy:
  provider: azure_web_apps
  skip_cleanup: true
  verbose: true
  on:
    all_branches: true
