language: node_js
node_js:
  - '7'
before_deploy:
  "git push origin master:refs/heads/master" \
  cd packages && cd office-ui-fabric-react
deploy:
  provider: azure_web_apps
  skip_cleanup: true
  verbose: true
  on:
    all_branches: true
